service: dynamodbbook-session-store

provider:
  name: aws
  runtime: dotnetcore3.1
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchWriteItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
      Resource:
        - Fn::GetAtt:
          - SessionStoreTable
          - Arn
        - Fn::Join:
          - '/'
          - - Fn::GetAtt:
              - SessionStoreTable
              - Arn
            - "index"
            - "UserIndex"
  environment:
    TABLE_NAME: { Ref: SessionStoreTable }
    INDEX_NAME: 'UserIndex'

package:
  individually: true

functions:
  createSession:
    handler: CsharpHandlers::DynamoDbBook.SessionStore.Serverless.CreateSessionHandler::CreateSession
    package:
      artifact: bin/Release/netcoreapp3.1/DynamoDbBook.SessionStore.zip
    events:
      - http:
          path: sessions
          method: post

resources:
  Resources:
    SessionStoreTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - AttributeName: "SessionId"
            AttributeType: "S"
          - AttributeName: "Username"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "SessionId"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        GlobalSecondaryIndexes: 
          - IndexName: "UserIndex"
            KeySchema: 
              - AttributeName: "Username"
                KeyType: "HASH"
            Projection:
              ProjectionType: "KEYS_ONLY"
        TimeToLiveSpecification:
          AttributeName: "TTL"
          Enabled: true
